baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Infrastructure M&A Tracker'
theme = 'infra-ma'

[params]
  description = 'Tracking infrastructure mergers and acquisitions transactions'
  author = 'Infra M&A Team'

[taxonomies]
  sector = 'sectors'
  status = 'statuses'
  tag = 'tags'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Deals'
    url = '/deals/'
    weight = 2
  [[menu.main]]
    name = 'Transactions'
    url = '/transactions/'
    weight = 3
  [[menu.main]]
    name = 'Sectors'
    url = '/sectors/'
    weight = 4
  [[menu.main]]
    name = 'Analysis'
    url = '/analysis/'
    weight = 5
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 6
