baseURL = 'https://mikeberry6.github.io/Infra-MA/'
languageCode = 'en-us'
title = 'Infra M&A'
theme = 'infra-ma'

[params]
  description = 'Infrastructure mergers & acquisitions tracker'
  tagline = 'Tracking capital flows across global infrastructure'

[taxonomies]
  sector = 'sectors'

[menu]
  [[menu.main]]
    name = 'Briefing'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Tracker'
    url = '/deals/'
    weight = 2
